import * as core from '@actions/core'
import type { GitHub } from '@actions/github/lib/utils.js'
import type { Context } from '@actions/github/lib/context.js'

const BRANCH_PREFIX = 'docpilot/update-'

export async function createOrUpdatePR(
  octokit: InstanceType<typeof GitHub>,
  context: Context,
  updatedContent: string,
  targetFile: string,
  summary: string,
  labels: string[],
  reviewers: string[]
): Promise<string> {
  const { owner, repo } = context.repo
  const baseBranch = context.ref.replace('refs/heads/', '')
  const headBranch = `${BRANCH_PREFIX}${targetFile.replace(/[^a-z0-9]/gi, '-').toLowerCase()}`

  // Check for existing open docpilot PR to avoid spam
  const existing = await findExistingPR(octokit, owner, repo, headBranch)

  if (existing) {
    core.info(`Updating existing PR #${existing.number}: ${existing.html_url}`)
    await pushUpdate(octokit, owner, repo, headBranch, targetFile, updatedContent, existing.head.sha)
    return existing.html_url
  }

  // Create new branch + PR
  core.info(`Creating new branch ${headBranch}`)
  const prUrl = await createNewPR(
    octokit, owner, repo,
    baseBranch, headBranch,
    context.sha,
    targetFile, updatedContent,
    summary, labels, reviewers
  )

  return prUrl
}

async function findExistingPR(
  octokit: InstanceType<typeof GitHub>,
  owner: string,
  repo: string,
  headBranch: string
): Promise<{ number: number; html_url: string; head: { sha: string } } | null> {
  const { data } = await octokit.rest.pulls.list({
    owner, repo,
    state: 'open',
    head: `${owner}:${headBranch}`,
  })
  return data[0] ?? null
}

async function createNewPR(
  octokit: InstanceType<typeof GitHub>,
  owner: string,
  repo: string,
  baseBranch: string,
  headBranch: string,
  baseSha: string,
  targetFile: string,
  content: string,
  summary: string,
  labels: string[],
  reviewers: string[]
): Promise<string> {
  const { data: baseCommit } = await octokit.rest.git.getCommit({
    owner, repo, commit_sha: baseSha,
  })

  const { data: blob } = await octokit.rest.git.createBlob({
    owner, repo,
    content: Buffer.from(content).toString('base64'),
    encoding: 'base64',
  })

  const { data: tree } = await octokit.rest.git.createTree({
    owner, repo,
    base_tree: baseCommit.tree.sha,
    tree: [{ path: targetFile, mode: '100644', type: 'blob', sha: blob.sha }],
  })

  const { data: commit } = await octokit.rest.git.createCommit({
    owner, repo,
    message: `docs: update ${targetFile}\n\nAuto-generated by docpilot`,
    tree: tree.sha,
    parents: [baseSha],
  })

  await octokit.rest.git.createRef({
    owner, repo,
    ref: `refs/heads/${headBranch}`,
    sha: commit.sha,
  })

  const { data: pr } = await octokit.rest.pulls.create({
    owner, repo,
    title: `docs: update ${targetFile}`,
    body: buildPRBody(summary),
    head: headBranch,
    base: baseBranch,
  })

  if (labels.length > 0) {
    await octokit.rest.issues.addLabels({
      owner, repo, issue_number: pr.number, labels,
    }).catch(err => core.warning(`Could not add labels: ${err}`))
  }

  if (reviewers.length > 0) {
    await octokit.rest.pulls.requestReviewers({
      owner, repo, pull_number: pr.number, reviewers,
    }).catch(err => core.warning(`Could not add reviewers: ${err}`))
  }

  return pr.html_url
}

async function pushUpdate(
  octokit: InstanceType<typeof GitHub>,
  owner: string,
  repo: string,
  headBranch: string,
  targetFile: string,
  content: string,
  currentHeadSha: string
): Promise<void> {
  const { data: headCommit } = await octokit.rest.git.getCommit({
    owner, repo, commit_sha: currentHeadSha,
  })

  const { data: blob } = await octokit.rest.git.createBlob({
    owner, repo,
    content: Buffer.from(content).toString('base64'),
    encoding: 'base64',
  })

  const { data: tree } = await octokit.rest.git.createTree({
    owner, repo,
    base_tree: headCommit.tree.sha,
    tree: [{ path: targetFile, mode: '100644', type: 'blob', sha: blob.sha }],
  })

  const { data: commit } = await octokit.rest.git.createCommit({
    owner, repo,
    message: `docs: update ${targetFile}\n\nAuto-generated by docpilot`,
    tree: tree.sha,
    parents: [currentHeadSha],
  })

  await octokit.rest.git.updateRef({
    owner, repo,
    ref: `heads/${headBranch}`,
    sha: commit.sha,
    force: false,
  })
}

function buildPRBody(summary: string): string {
  return `## docpilot: Documentation Update

${summary}

---
*Auto-generated by [docpilot](https://github.com/robinchoice/docpilot). Review and merge if the changes look correct.*`
}
