import * as core from '@actions/core'
import type { GitHub } from '@actions/github/lib/utils'
import type { context } from '@actions/github'

type Context = typeof context

const BRANCH_PREFIX = 'docpilot/update-'

export async function createOrUpdatePR(
  octokit: InstanceType<typeof GitHub>,
  context: Context,
  updatedContent: string,
  targetFile: string,
  summary: string,
  labels: string[],
  reviewers: string[]
): Promise<string> {
  const { owner, repo } = context.repo
  const baseBranch = context.ref.replace('refs/heads/', '')
  const headBranch = `${BRANCH_PREFIX}${targetFile.replace(/[^a-z0-9]/gi, '-').toLowerCase()}`

  // Check for existing open docpilot PR to avoid spam
  const existing = await findExistingPR(octokit, owner, repo, headBranch)

  if (existing) {
    core.info(`Updating existing PR #${existing.number}: ${existing.html_url}`)
    const commitSha = await commitFile(octokit, owner, repo, existing.head.sha, targetFile, updatedContent)
    await octokit.rest.git.updateRef({
      owner, repo,
      ref: `heads/${headBranch}`,
      sha: commitSha,
    })
    await octokit.rest.pulls.update({
      owner, repo, pull_number: existing.number,
      body: buildPRBody(summary),
    })
    return existing.html_url
  }

  // Create new branch + PR
  core.info(`Creating new branch ${headBranch}`)
  const commitSha = await commitFile(octokit, owner, repo, context.sha, targetFile, updatedContent)

  await octokit.rest.git.createRef({
    owner, repo,
    ref: `refs/heads/${headBranch}`,
    sha: commitSha,
  })

  const { data: pr } = await octokit.rest.pulls.create({
    owner, repo,
    title: `docs: update ${targetFile}`,
    body: buildPRBody(summary),
    head: headBranch,
    base: baseBranch,
  })

  if (labels.length > 0) {
    await octokit.rest.issues.addLabels({
      owner, repo, issue_number: pr.number, labels,
    }).catch(err => core.warning(`Could not add labels: ${err}`))
  }

  if (reviewers.length > 0) {
    await octokit.rest.pulls.requestReviewers({
      owner, repo, pull_number: pr.number, reviewers,
    }).catch(err => core.warning(`Could not add reviewers: ${err}`))
  }

  return pr.html_url
}

async function findExistingPR(
  octokit: InstanceType<typeof GitHub>,
  owner: string,
  repo: string,
  headBranch: string
): Promise<{ number: number; html_url: string; head: { sha: string } } | null> {
  const { data } = await octokit.rest.pulls.list({
    owner, repo,
    state: 'open',
    head: `${owner}:${headBranch}`,
  })
  return data[0] ?? null
}

async function commitFile(
  octokit: InstanceType<typeof GitHub>,
  owner: string,
  repo: string,
  parentSha: string,
  path: string,
  content: string
): Promise<string> {
  const { data: parent } = await octokit.rest.git.getCommit({
    owner, repo, commit_sha: parentSha,
  })
  const { data: tree } = await octokit.rest.git.createTree({
    owner, repo,
    base_tree: parent.tree.sha,
    tree: [{ path, mode: '100644', type: 'blob', content }],
  })
  const { data: commit } = await octokit.rest.git.createCommit({
    owner, repo,
    message: `docs: update ${path}\n\nAuto-generated by docpilot`,
    tree: tree.sha,
    parents: [parentSha],
  })
  return commit.sha
}

function buildPRBody(summary: string): string {
  return `## docpilot: Documentation Update

${summary}

---
*Auto-generated by [docpilot](https://github.com/robinchoice/docpilot). Review and merge if the changes look correct.*`
}
